require-stack-version: ">= 1.4"

resolver: lts-10.0

packages:
- .
- apps/als
- apps/argv
- apps/bench
- apps/dataframe
- apps/hello
- apps/lda
- apps/rdd-ops

extra-deps:
- inline-java-0.8.1
- jni-0.6.0
- jvm-0.4.2
- jvm-batching-0.1.1
- jvm-streaming-0.3
- distributed-closure-0.4.0

nix:
  # Requires Stack >= 1.2.
  shell-file: shell.nix
  path: ["nixpkgs=./nixpkgs.nix"]

docker:
  enable: false
  image: tweag/sparkle
  run-args: ["--net=bridge"]
  stack-exe: image
